cmake_minimum_required(VERSION 4.2)
project(C___)

set(CMAKE_CXX_STANDARD 14)

add_executable(C___
        c++_prime/while/ex_1_4_1.cpp
        calculator/my_calculator.cpp
        car/car.cpp
        "chapter 1 algorithms/salepersonBonus.cpp"
        "chapter 1 algorithms/studrntMarks.cpp"
        class_homework/hw6_1.cpp
        class_homework/hw_5.cpp
        class_homework/hw_5_2.cpp
        class_homework/hw_7_1.cpp
        class_homework/hw_7_2.cpp
        class_homework/hw_7_3.cpp
        class_homework/hw_7_4.cpp
        class_homework/hw_7_5.cpp
        class_homework/hw_8_1.cpp
        class_homework/hw_8_2.cpp
        class_homework/tempCodeRunnerFile.cpp
        "lab home work/hw_1/helloworld.cpp"
        "lab home work/hw_1/hw_1.cpp"
        "lab home work/hw_10/hw_10_1largest_of_1_numbers.cpp"
        "lab home work/hw_10/hw_10_2_abs.cpp"
        "lab home work/hw_10/hw_10_3munnit_to_second.cpp"
        "lab home work/hw_10/hw_10_4doubleNumber.cpp"
        "lab home work/hw_10/hw_10_5factorial.cpp"
        "lab home work/hw_10/tempCodeRunnerFile.cpp"
        "lab home work/hw_3_files/hw_3_code_of_the_day.cpp"
        "lab home work/hw_3_files/hw_3_miles_to_kilometers.cpp"
        "lab home work/hw_3_files/hw_3_rectsngle_area.cpp"
        "lab home work/hw_3_files/hw_3_store3_intergers.cpp"
        "lab home work/hw_3_files/tempCodeRunnerFile.cpp"
        "lab home work/hw_3_files/tutorial_3.cpp"
        "lab home work/hw_5/hw_5_1.cpp"
        "lab home work/hw_5/hw_5_2.cpp"
        "lab home work/hw_5/hw_5_3.cpp"
        "lab home work/hw_7/hw_7.cpp"
        "lab home work/hw_7/q5.cpp"
        "lab home work/hw_7/while_loop.cpp"
        "lab home work/hw_8/hw_8_1.cpp"
        "lab home work/hw_8/hw_8_3.cpp"
        "lab home work/hw_8/hw_8_4.cpp"
        "lab home work/hw_8/hw_8_5.cpp"
        "lab home work/hw_8/hw_8_6.cpp"
        "lab home work/hw_9/hw_9_1.cpp"
        "lab home work/hw_9/hw_9_2.cpp"
        "lab home work/hw_9/hw_9_3.cpp"
        "lab home work/hw_9/hw_9_4.cpp"
        "lab home work/hw_9/hw_9_5.cpp"
        "lab home work/for_loop.cpp"
        "lab home work/hw_2.cpp"
        "lab home work/hw_6_2.cpp"
        "lab home work/tempCodeRunnerFile.cpp"
        "lab home work/tutorial2.cpp"
        practice/breck_continue.cpp
        practice/loop.cpp
        practice/loop_for.cpp
        "student management system/main.cpp"
        "student management system/students.cpp"
        "student management system/tempCodeRunnerFile.cpp"
        usd_to_SAR_converter/avrage_addentify.cpp
        usd_to_SAR_converter/driving_age.cpp
        usd_to_SAR_converter/student_grade_app.cpp
        usd_to_SAR_converter/usd_to_asr.cpp)
